spring:
  datasource:
    url: jdbc:mysql://192.168.139.102 :3306/coursedesign?characterEncoding=utf-8
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
server:
  port: 8083